name: Build .NET SDK

on: [workflow_dispatch]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      run: |
        git clone --depth 1 -b v9.0.0-preview.7.24405.7 https://github.com/dotnet/dotnet

    - name: Build
      run: |
        docker run --platform linux/amd64 --rm -v${{ github.workspace }}/dotnet:/dotnet -e ROOTFS_DIR=/crossrootfs/riscv64 \
          mcr.microsoft.com/dotnet-buildtools/prereqs:azurelinux-3.0-cross-riscv64-net9.0 \
          sh -c 'cd /dotnet && ./prep-source-build.sh && ./build.sh -sb --clean-while-building /p:TargetOS=linux /p:TargetArchitecture=riscv64'

    - name: Upload .NET
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-sdk-linux-riscv64
        path: "${{ github.workspace }}/dotnet/artifacts/assets/Release/*"
